version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: ./devtools/docker/Dockerfile
    image: pc/identidade
    container_name: pc-identidade-app
    restart: unless-stopped
    ports:
      - "8000:8000"
    networks:
      - pc-net
    env_file:
      - .env
    depends_on:
      - mongodb
      - keycloak

  mongodb:
    image: mongo:8.0
    container_name: pc-identidade-mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: bd01
    volumes:
      - mongo_data:/data/db
    networks:
      - pc-net

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.5
    container_name: pc-identidade-keycloak
    ports:
      - "8080:8080"
      - "8443:8443"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://pc-identidade-keycloak-db:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password
      KC_HOSTNAME: pc-identidade-keycloak
      KC_HTTP_ENABLED: 'true'
      KC_HEALTH_ENABLED: 'true'
      KC_METRICS_ENABLED: 'true'
      KC_FEATURES: token-exchange
      KC_IMPORT_FILES: /opt/keycloak/data/import/marketplace-realm.json
      KC_IMPORT_STRATEGY: ignore_existing
    volumes:
      - ./devtools/keycloak-config:/opt/keycloak/data/import
    depends_on:
      - keycloak-db
    command: [ "start-dev", "--import-realm" ]
    restart: unless-stopped
    networks:
      - pc-net

  keycloak-db:
    image: postgres:13
    container_name: pc-identidade-keycloak-db
    hostname: pc-identidade-keycloak-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    restart: unless-stopped
    networks:
      - pc-net


networks:
  pc-net:
    driver: bridge

volumes:
  mongo_data: