# docker-compose.yml

# Definindo a versão do Compose para garantir compatibilidade com os recursos usados
version: '3.8'

services:
  ######################################################
  # <<< NOVO: SERVIÇO PARA SUA APLICAÇÃO FASTAPI >>>
  ######################################################
  app:
    # 'build' instrui o Compose a construir a imagem a partir de um Dockerfile.
    # Isso substitui seu comando 'docker build' manual.
    build:
      context: . # O contexto é o diretório raiz do seu projeto.
      dockerfile: ./devtools/docker/Dockerfile # O caminho para o seu Dockerfile.
    image: pc/identidade # <<< Opcional, mas boa prática: nomeia a imagem construída.
    container_name: pc-identidade-app # <<< Define um nome fixo para o container.
    restart: unless-stopped
    ports:
      - "8000:8000" # Mapeia a porta do container para o seu host.
    env_file:
      - .env # Carrega as variáveis de ambiente do seu arquivo .env.
    networks:
      - pc-net # <<< Conecta este serviço à nossa rede compartilhada.
    depends_on:
      # Garante que o banco e o Keycloak iniciem ANTES da sua aplicação.
      - mongodb
      - keycloak

  ################################################
  # SERVIÇO DO MONGODB (COM AJUSTES)
  ################################################
  mongodb:
    image: mongo:8.0
    container_name: pc-identidade-mongo # <<< ALTERADO: Nome fixo para comunicação fácil.
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: bd01
    volumes:
      - mongo_data:/data/db
    networks:
      - pc-net # <<< ALTERADO: Conecta à rede compartilhada.

  ################################################
  # SERVIÇO DO KEYCLOAK (COM AJUSTES)
  ################################################
  keycloak:
    image: quay.io/keycloak/keycloak:24.0.5
    container_name: pc-identidade-keycloak # <<< ALTERADO: Nome fixo.
    ports:
      - "8080:8080"
      - "8443:8443"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      # <<< ALTERADO: usa o nome do serviço do banco de dados do Keycloak.
      KC_DB_URL: jdbc:postgresql://pc-identidade-keycloak-db:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password
      KC_HOSTNAME: localhost
      KC_HTTP_ENABLED: 'true'
      KC_HEALTH_ENABLED: 'true'
      KC_METRICS_ENABLED: 'true'
      KC_FEATURES: token-exchange
      KC_IMPORT_FILES: /opt/keycloak/data/import/marketplace-realm.json
      KC_IMPORT_STRATEGY: ignore_existing
    volumes:
      - ./devtools/keycloak-config:/opt/keycloak/data/import
    depends_on:
      - keycloak-db
    command: [ "start-dev", "--import-realm" ]
    restart: unless-stopped
    networks:
      - pc-net # <<< ALTERADO: Conecta à rede compartilhada.

  ################################################
  # SERVIÇO DO BANCO DO KEYCLOAK (COM AJUSTES)
  ################################################
  keycloak-db:
    image: postgres:13
    container_name: pc-identidade-keycloak-db # <<< ALTERADO: Nome fixo.
    hostname: pc-identidade-keycloak-db # <<< ALTERADO: Garante o hostname interno.
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    restart: unless-stopped
    networks:
      - pc-net # <<< ALTERADO: Conecta à rede compartilhada.


######################################################
# <<< NOVO: DEFINIÇÃO DA REDE COMPARTILHADA >>>
######################################################
networks:
  pc-net:
    driver: bridge # O driver padrão para redes locais.

volumes:
  mongo_data: