version: '3.8'

services:
  mongodb:
    image: mongo:8.0
    container_name: pc-identidade-mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: bd01
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    volumes:
      - mongo_data:/data/db

  mongodb-cold:
    image: mongo:8.0
    container_name: pc-identidade-mongo-cold
    restart: always
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin_cold
      MONGO_INITDB_ROOT_PASSWORD: admin_cold
      MONGO_INITDB_DATABASE: bd01_cold
    volumes:
      - mongo_data_cold:/data/db

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.5
    container_name: pc-identidade-keycloak
    ports:
      - "8080:8080"
      - "8443:8443"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak-db:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password
      KC_HOSTNAME: localhost
      KC_HTTP_ENABLED: 'true'
      KC_HEALTH_ENABLED: 'true'
      KC_METRICS_ENABLED: 'true'
      KC_FEATURES: token-exchange
      KC_IMPORT_FILES: /opt/keycloak/data/import/marketplace-realm.json
      KC_IMPORT_STRATEGY: ignore_existing
      # Configurações para envio de email via Keycloak
      KC_SMTP_SERVER_HOST: smtp.gmail.com
      KC_SMTP_SERVER_PORT: 587
      KC_SMTP_SERVER_AUTH: "true"
      KC_SMTP_SERVER_STARTTLS: "true"
      KC_SMTP_SERVER_USER: joaopedrovr91@gmail.com
      KC_SMTP_SERVER_PASSWORD: "[INSERIR SENHA DE APP AQ]"
      KC_SPI_EMAIL_FROM: joaopedrovr91@gmail.com
      KC_SPI_EMAIL_FROM_NAME: "PC-Identidade"
    volumes:
      - ./devtools/keycloak-config:/opt/keycloak/data/import
    depends_on:
      - keycloak-db
    command: [ "start-dev", "--import-realm" ]
    restart: unless-stopped


  keycloak-db:
    image: postgres:13
    container_name: pc-identidade-keycloak-db
    hostname: keycloak-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    restart: unless-stopped
    # volumes:
    #   - pgdata:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:4-management
    container_name: pc-identidade-rabbitmq
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    volumes:
      - ./definitions.json:/etc/rabbitmq/definitions.json:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_port_connectivity"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
      
  rabbitmq-setup:
    image: curlimages/curl:latest
    depends_on:
      rabbitmq:
        condition: service_healthy
    volumes:
      - ./definitions.json:/tmp/definitions.json:ro
    command: sh -c "
        echo 'Aguardando RabbitMQ estar pronto...' &&
        sleep 10 &&
        echo 'Carregando definições...' &&
        curl -u admin:admin -X POST -H 'Content-Type:application/json' -d @/tmp/definitions.json http://rabbitmq:15672/api/definitions &&
        echo 'Definições carregadas com sucesso!'
      "
    restart: "no"
    
  redis:
    image: redis:7-alpine
    container_name: pc-identidade-redis
    hostname: redis
    ports:
      - "6379:6379"
    restart: unless-stopped
    volumes:
      - redis_data:/data

volumes:
  mongo_data:
  rabbitmq_data:
  mongo_data_cold:
  redis_data:
