services:
  mongodb:
    image: mongo:8.0
    container_name: pc-identidade-mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: bd01
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: